export const INDIAN_BANKS = [
    "State Bank of India",
    "Bank of Baroda",
    "Bank of India",
    "Canara Bank",
    "Central Bank of India",
    "Indian Bank",
    "Indian Overseas Bank",
    "UCO Bank",
    "Union Bank of India",
    "Punjab National Bank",
    "Punjab & Sind Bank",
    "Bank of Maharashtra",
    "Axis Bank",
    "HDFC Bank",
    "ICICI Bank",
    "Kotak Mahindra Bank",
    "IDBI Bank",
    "IndusInd Bank",
    "Dhanlaxmi Bank",
    "City Union Bank",
    "Bandhan Bank",
    "Andhra Pradesh Grameena Bank",
    "Chaitanya Godavari Grameena Bank",
    "Telangana Grameena Bank",
    "Tamilnadu Bank",
    "Karur Vysya Bank",
    "Federal Bank",
    "South Indian Bank",
    "Karnataka Bank",
    "Tamilnad Bank",
    "IDFC First Bank",
    "Yes Bank",
    "HDB"
] as const;
